using LouBarbershop.Application.Inventory;
using LouBarbershop.Domain.Catalog;
using LouBarbershop.Domain.Expenses;
using LouBarbershop.Domain.Inventory;
using LouBarbershop.Domain.Sales;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;

namespace LouBarbershop.Infrastructure.Persistence;

public sealed class EfInventoryStore(AppDbContext db) : IInventoryStore
{
    public async Task<IInventoryTransaction> BeginAsync(CancellationToken ct) { var transaction = await db.Database.BeginTransactionAsync(ct); await db.Database.ExecuteSqlRawAsync("SELECT pg_advisory_xact_lock(8012026)", ct); return new Transaction(transaction); }
    public Task<Product?> FindProductAsync(Guid id, CancellationToken ct) => db.Products.SingleOrDefaultAsync(x => x.Id == id, ct);
    public async Task<int> QuantityAsync(Guid productId, CancellationToken ct) => await db.InventoryMovements.Where(x => x.ProductId == productId).SumAsync(x => (int?)x.QuantityDelta, ct) ?? 0;
    public Task<bool> ExpenseCategoryActiveAsync(Guid id, CancellationToken ct) => db.ExpenseCategories.AnyAsync(x => x.Id == id && x.Active, ct);
    public Task<Expense?> FindExpenseAsync(Guid id, CancellationToken ct) => db.Expenses.SingleOrDefaultAsync(x => x.Id == id, ct);
    public async Task<IReadOnlyCollection<InventoryView>> ListInventoryAsync(CancellationToken ct) => await db.Products.AsNoTracking().OrderBy(x => x.Name).Select(x => new InventoryView(x.Id, x.Name, x.Sku, x.SalePrice.Cents, x.AverageCost.Cents, db.InventoryMovements.Where(m => m.ProductId == x.Id).Sum(m => (int?)m.QuantityDelta) ?? 0, x.MinimumStock, (db.InventoryMovements.Where(m => m.ProductId == x.Id).Sum(m => (int?)m.QuantityDelta) ?? 0) <= x.MinimumStock, x.Active)).ToArrayAsync(ct);
    public async Task<IReadOnlyCollection<MovementView>> ListMovementsAsync(Guid productId, CancellationToken ct) => await db.InventoryMovements.AsNoTracking().Where(x => x.ProductId == productId).OrderByDescending(x => x.OccurredAt).Select(x => new MovementView(x.Id, x.ProductId, x.Type, x.QuantityDelta, x.UnitCostCents, x.Reason, x.OccurredAt)).ToArrayAsync(ct);
    public async Task<IReadOnlyCollection<ReceiptView>> ListReceiptsAsync(CancellationToken ct) => await db.InventoryReceipts.AsNoTracking().OrderByDescending(x => x.ReceiptDate).ThenByDescending(x => x.CreatedAt).Select(x => new ReceiptView(x.Id, x.ReceiptDate, x.PaymentMethod, x.TotalCents, x.Reference, x.Note, x.Status, x.CreatedAt, x.Version, x.Items.Select(i => new ReceiptItemView(i.Id, i.ProductId, db.Products.Where(p => p.Id == i.ProductId).Select(p => p.Name).Single(), i.Quantity, i.UnitCostCents, i.LineTotalCents)).ToArray())).ToArrayAsync(ct);
    public async Task<IReadOnlyCollection<ExpenseView>> ListExpensesAsync(DateOnly? dateFrom, DateOnly? dateTo, CancellationToken ct) => await (from expense in db.Expenses.AsNoTracking() join category in db.ExpenseCategories.AsNoTracking() on expense.CategoryId equals category.Id where (!dateFrom.HasValue || expense.ExpenseDate >= dateFrom) && (!dateTo.HasValue || expense.ExpenseDate <= dateTo) orderby expense.ExpenseDate descending select new ExpenseView(expense.Id, expense.CategoryId, category.Name, expense.ExpenseDate, expense.Description, expense.AmountCents, expense.PaymentMethod, expense.Status, expense.VoidReason, expense.Version)).ToArrayAsync(ct);
    public async Task<CashFlowView> CashFlowAsync(DateOnly dateFrom, DateOnly dateTo, CancellationToken ct)
    { var zone = TimeZoneInfo.FindSystemTimeZoneById("America/La_Paz"); var start = new DateTimeOffset(TimeZoneInfo.ConvertTimeToUtc(dateFrom.ToDateTime(TimeOnly.MinValue, DateTimeKind.Unspecified), zone)); var end = new DateTimeOffset(TimeZoneInfo.ConvertTimeToUtc(dateTo.AddDays(1).ToDateTime(TimeOnly.MinValue, DateTimeKind.Unspecified), zone)); var payments = db.Payments.AsNoTracking().Where(x => x.PaidAt >= start && x.PaidAt < end); var receipts = db.InventoryReceipts.AsNoTracking().Where(x => x.ReceiptDate >= dateFrom && x.ReceiptDate <= dateTo && x.Status == InventoryReceiptStatus.Confirmed); var expenses = db.Expenses.AsNoTracking().Where(x => x.ExpenseDate >= dateFrom && x.ExpenseDate <= dateTo && x.Status == ExpenseStatus.Recorded); var salesCash = await payments.Where(x => x.Method == PaymentMethod.Cash).SumAsync(x => (long?)x.AmountCents, ct) ?? 0; var salesQr = await payments.Where(x => x.Method == PaymentMethod.Qr).SumAsync(x => (long?)x.AmountCents, ct) ?? 0; var inventoryCash = await receipts.Where(x => x.PaymentMethod == PaymentMethod.Cash).SumAsync(x => (long?)x.TotalCents, ct) ?? 0; var inventoryQr = await receipts.Where(x => x.PaymentMethod == PaymentMethod.Qr).SumAsync(x => (long?)x.TotalCents, ct) ?? 0; var expenseCash = await expenses.Where(x => x.PaymentMethod == PaymentMethod.Cash).SumAsync(x => (long?)x.AmountCents, ct) ?? 0; var expenseQr = await expenses.Where(x => x.PaymentMethod == PaymentMethod.Qr).SumAsync(x => (long?)x.AmountCents, ct) ?? 0; return new(dateFrom, dateTo, salesCash, salesQr, inventoryCash, inventoryQr, expenseCash, expenseQr, salesCash - inventoryCash - expenseCash, salesQr - inventoryQr - expenseQr); }
    public void Add(InventoryReceipt value) => db.InventoryReceipts.Add(value); public void Add(InventoryMovement value) => db.InventoryMovements.Add(value); public void Add(Expense value) => db.Expenses.Add(value); public Task SaveChangesAsync(CancellationToken ct) => db.SaveChangesAsync(ct);
    private sealed class Transaction(IDbContextTransaction value) : IInventoryTransaction { public Task CommitAsync(CancellationToken ct) => value.CommitAsync(ct); public ValueTask DisposeAsync() => value.DisposeAsync(); }
}
