// <auto-generated />
using System;
using System.Collections.Generic;
using LouBarbershop.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LouBarbershop.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908235544_AddCommissionSettlements")]
    partial class AddCommissionSettlements
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("lou")
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LouBarbershop.Domain.Appointments.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid")
                        .HasColumnName("barber_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("customer_note");

                    b.Property<string>("ManagementTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("management_token_hash");

                    b.Property<int>("QuotedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("quoted_duration_minutes");

                    b.Property<long>("QuotedPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("quoted_price_cents");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Range", "LouBarbershop.Domain.Appointments.Appointment.Range#TimeRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("EndsAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ends_at");

                            b1.Property<DateTimeOffset>("StartsAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("starts_at");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BarberId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId");

                    b.ToTable("appointments", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Catalog.BarberServiceOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid")
                        .HasColumnName("barber_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price_cents");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "LouBarbershop.Domain.Catalog.BarberServiceOffering.Period#EffectivePeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("BarberId", "ServiceId")
                        .HasDatabaseName("ix_offerings_barber_service");

                    b.ToTable("barber_service_offerings", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Catalog.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<long>("AverageCost")
                        .HasColumnType("bigint")
                        .HasColumnName("average_cost_cents");

                    b.Property<string>("Brand")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("brand");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<long>("SalePrice")
                        .HasColumnType("bigint")
                        .HasColumnName("sale_price_cents");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("ux_products_sku")
                        .HasFilter("sku IS NOT NULL");

                    b.ToTable("products", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Catalog.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DefaultDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("default_duration_minutes");

                    b.Property<long>("DefaultPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("default_price_cents");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_services_name");

                    b.ToTable("services", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Commissions.CommissionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid")
                        .HasColumnName("barber_id");

                    b.Property<long>("BaseCents")
                        .HasColumnType("bigint")
                        .HasColumnName("base_cents");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("EarnedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earned_at");

                    b.Property<int>("RateBasisPoints")
                        .HasColumnType("integer")
                        .HasColumnName("rate_basis_points");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("SaleItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_item_id");

                    b.Property<Guid?>("SourceEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_entry_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entry_type");

                    b.HasKey("Id");

                    b.HasIndex("BarberId");

                    b.HasIndex("SaleItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_commission_entries_sale_item")
                        .HasFilter("sale_item_id IS NOT NULL");

                    b.HasIndex("SourceEntryId")
                        .IsUnique()
                        .HasDatabaseName("ux_commission_entries_source")
                        .HasFilter("source_entry_id IS NOT NULL");

                    b.ToTable("commission_entries", "lou", t =>
                        {
                            t.HasCheckConstraint("ck_commission_entries_source", "(entry_type = 'Earning' AND sale_item_id IS NOT NULL AND source_entry_id IS NULL) OR (entry_type = 'Reversal' AND sale_item_id IS NULL AND source_entry_id IS NOT NULL AND reason IS NOT NULL)");

                            t.HasCheckConstraint("ck_commission_entries_values", "base_cents >= 0 AND rate_basis_points >= 0 AND rate_basis_points <= 10000 AND ((entry_type = 'Earning' AND amount_cents >= 0) OR (entry_type = 'Reversal' AND amount_cents <= 0))");
                        });
                });

            modelBuilder.Entity("LouBarbershop.Domain.Commissions.CommissionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid")
                        .HasColumnName("barber_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<int>("Rate")
                        .HasColumnType("integer")
                        .HasColumnName("rate_basis_points");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "LouBarbershop.Domain.Commissions.CommissionRule.Period#EffectivePeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BarberId", "Kind")
                        .HasDatabaseName("ix_commission_rules_barber_kind");

                    b.ToTable("commission_rules", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Commissions.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AdjustmentTotalCents")
                        .HasColumnType("bigint")
                        .HasColumnName("adjustment_total_cents");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid")
                        .HasColumnName("barber_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid?>("ClosedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("closed_by");

                    b.Property<long>("CommissionTotalCents")
                        .HasColumnType("bigint")
                        .HasColumnName("commission_total_cents");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("PaidBy")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by");

                    b.Property<long>("PayableTotalCents")
                        .HasColumnType("bigint")
                        .HasColumnName("payable_total_cents");

                    b.Property<DateOnly?>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("payment_method");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("BarberId", "PeriodEnd")
                        .HasDatabaseName("ix_settlements_barber_period");

                    b.ToTable("settlements", "lou", t =>
                        {
                            t.HasCheckConstraint("ck_settlements_period", "period_end >= period_start");

                            t.HasCheckConstraint("ck_settlements_totals", "payable_total_cents = commission_total_cents + adjustment_total_cents AND payable_total_cents >= 0");
                        });
                });

            modelBuilder.Entity("LouBarbershop.Domain.Commissions.SettlementAdjustment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<Guid>("AuthorizedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("authorized_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_id");

                    b.HasKey("Id");

                    b.HasIndex("SettlementId");

                    b.ToTable("settlement_adjustments", "lou", t =>
                        {
                            t.HasCheckConstraint("ck_settlement_adjustments_amount", "amount_cents <> 0");
                        });
                });

            modelBuilder.Entity("LouBarbershop.Domain.Commissions.SettlementItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<Guid>("CommissionEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("commission_entry_id");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_id");

                    b.HasKey("Id");

                    b.HasIndex("CommissionEntryId")
                        .IsUnique()
                        .HasDatabaseName("ux_settlement_items_commission_entry");

                    b.HasIndex("SettlementId");

                    b.ToTable("settlement_items", "lou", t =>
                        {
                            t.HasCheckConstraint("ck_settlement_items_amount", "amount_cents <> 0");
                        });
                });

            modelBuilder.Entity("LouBarbershop.Domain.Customers.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_e164");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .HasDatabaseName("ix_customers_display_name");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("ix_customers_phone_e164");

                    b.ToTable("customers", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Expenses.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date")
                        .HasColumnName("expense_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("payment_method");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("void_reason");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("voided_at");

                    b.Property<Guid?>("VoidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("voided_by");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ExpenseDate", "Status")
                        .HasDatabaseName("ix_expenses_date_status");

                    b.ToTable("expenses", "lou", t =>
                        {
                            t.HasCheckConstraint("ck_expenses_amount", "amount_cents > 0");
                        });
                });

            modelBuilder.Entity("LouBarbershop.Domain.Expenses.ExpenseCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_expense_categories_name");

                    b.ToTable("expense_categories", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Inventory.InventoryMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityDelta")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_delta");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReceiptItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_item_id");

                    b.Property<Guid?>("SaleItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("sale_item_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("movement_type");

                    b.Property<long>("UnitCostCents")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_cost_cents");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptItemId")
                        .IsUnique();

                    b.HasIndex("SaleItemId");

                    b.HasIndex("ProductId", "OccurredAt")
                        .HasDatabaseName("ix_inventory_movements_product_time");

                    b.ToTable("inventory_movements", "lou", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_movements_cost", "unit_cost_cents >= 0");

                            t.HasCheckConstraint("ck_inventory_movements_quantity", "quantity_delta <> 0");
                        });
                });

            modelBuilder.Entity("LouBarbershop.Domain.Inventory.InventoryReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("payment_method");

                    b.Property<DateOnly>("ReceiptDate")
                        .HasColumnType("date")
                        .HasColumnName("receipt_date");

                    b.Property<string>("Reference")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("reference");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<long>("TotalCents")
                        .HasColumnType("bigint")
                        .HasColumnName("total_cents");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ReceiptDate")
                        .HasDatabaseName("ix_inventory_receipts_date");

                    b.ToTable("inventory_receipts", "lou", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_receipts_total", "total_cents > 0");
                        });
                });

            modelBuilder.Entity("LouBarbershop.Domain.Inventory.InventoryReceiptItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("LineTotalCents")
                        .HasColumnType("bigint")
                        .HasColumnName("line_total_cents");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("ReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("receipt_id");

                    b.Property<long>("UnitCostCents")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_cost_cents");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptId", "ProductId")
                        .IsUnique()
                        .HasDatabaseName("ux_inventory_receipt_items_product");

                    b.ToTable("inventory_receipt_items", "lou", t =>
                        {
                            t.HasCheckConstraint("ck_inventory_receipt_items_cost", "unit_cost_cents > 0 AND line_total_cents = quantity * unit_cost_cents");

                            t.HasCheckConstraint("ck_inventory_receipt_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("LouBarbershop.Domain.Sales.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_cents");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("method");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.HasKey("Id");

                    b.HasIndex("OperationId", "Method")
                        .IsUnique()
                        .HasDatabaseName("ux_payments_operation_method");

                    b.ToTable("payments", "lou", t =>
                        {
                            t.HasCheckConstraint("ck_payments_amount", "amount_cents > 0");
                        });
                });

            modelBuilder.Entity("LouBarbershop.Domain.Sales.SaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid")
                        .HasColumnName("barber_id");

                    b.Property<string>("DescriptionSnapshot")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("description_snapshot");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("type");

                    b.Property<long>("UnitCostCents")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_cost_cents");

                    b.Property<long>("UnitPriceCents")
                        .HasColumnType("bigint")
                        .HasColumnName("unit_price_cents");

                    b.HasKey("Id");

                    b.HasIndex("BarberId");

                    b.HasIndex("OperationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ServiceId");

                    b.ToTable("sale_items", "lou", t =>
                        {
                            t.HasCheckConstraint("ck_sale_items_reference", "(type = 'Service' AND service_id IS NOT NULL AND product_id IS NULL) OR (type = 'Product' AND service_id IS NULL AND product_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_sale_items_values", "unit_price_cents >= 0 AND unit_cost_cents >= 0 AND quantity > 0");
                        });
                });

            modelBuilder.Entity("LouBarbershop.Domain.Sales.SaleOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdjustmentReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("adjustment_reason");

                    b.Property<Guid?>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid")
                        .HasColumnName("barber_id");

                    b.Property<long>("CourtesyCents")
                        .HasColumnType("bigint")
                        .HasColumnName("courtesy_cents");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<long>("DiscountCents")
                        .HasColumnType("bigint")
                        .HasColumnName("discount_cents");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("ReversalReason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reversal_reason");

                    b.Property<DateTimeOffset?>("ReversedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reversed_at");

                    b.Property<Guid?>("ReversedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reversed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<long>("SubtotalCents")
                        .HasColumnType("bigint")
                        .HasColumnName("subtotal_cents");

                    b.Property<long>("TotalCents")
                        .HasColumnType("bigint")
                        .HasColumnName("total_cents");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("ux_sale_operations_appointment")
                        .HasFilter("appointment_id IS NOT NULL");

                    b.HasIndex("BarberId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OpenedAt", "Status")
                        .HasDatabaseName("ix_sale_operations_opened_status");

                    b.ToTable("sale_operations", "lou", t =>
                        {
                            t.HasCheckConstraint("ck_sale_operations_non_negative", "subtotal_cents >= 0 AND discount_cents >= 0 AND courtesy_cents >= 0 AND total_cents >= 0");

                            t.HasCheckConstraint("ck_sale_operations_total", "total_cents = subtotal_cents - discount_cents - courtesy_cents");
                        });
                });

            modelBuilder.Entity("LouBarbershop.Domain.Scheduling.AvailabilityExceptionRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid")
                        .HasColumnName("barber_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("kind");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Range", "LouBarbershop.Domain.Scheduling.AvailabilityExceptionRule.Range#TimeRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("EndsAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ends_at");

                            b1.Property<DateTimeOffset>("StartsAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("starts_at");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BarberId", "Active")
                        .HasDatabaseName("ix_availability_exceptions_barber_active");

                    b.ToTable("availability_exceptions", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Scheduling.WorkingSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<Guid>("BarberId")
                        .HasColumnType("uuid")
                        .HasColumnName("barber_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TimeOnly>("EndLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_local_time");

                    b.Property<TimeOnly>("StartLocalTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_local_time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Weekday")
                        .HasColumnType("integer")
                        .HasColumnName("weekday");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Period", "LouBarbershop.Domain.Scheduling.WorkingSchedule.Period#EffectivePeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateOnly>("ValidFrom")
                                .HasColumnType("date")
                                .HasColumnName("valid_from");

                            b1.Property<DateOnly?>("ValidTo")
                                .HasColumnType("date")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BarberId", "Weekday")
                        .HasDatabaseName("ix_working_schedules_barber_weekday");

                    b.ToTable("working_schedules", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Staff.BarberProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("employment_type");

                    b.Property<string>("SettlementFrequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("settlement_frequency");

                    b.Property<Guid>("StaffProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("staff_profile_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("StaffProfileId")
                        .IsUnique()
                        .HasDatabaseName("ux_barber_profiles_staff_id");

                    b.ToTable("barber_profiles", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Staff.StaffProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("display_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_staff_profiles_user_id");

                    b.ToTable("staff_profiles", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Infrastructure.Identity.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Infrastructure.Identity.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Infrastructure.Persistence.AppointmentEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("AfterData")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("after_data");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<string>("BeforeData")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_data");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId", "OccurredAt")
                        .HasDatabaseName("ix_appointment_events_appointment_time");

                    b.ToTable("appointment_events", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Infrastructure.Persistence.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("AfterData")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_data");

                    b.Property<string>("BeforeData")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_data");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entity_type");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_id");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "CreatedAt")
                        .HasDatabaseName("ix_audit_logs_entity_created_at");

                    b.ToTable("audit_logs", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Infrastructure.Persistence.IdempotencyRow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_idempotency_key_hash");

                    b.HasIndex("OperationId")
                        .IsUnique()
                        .HasDatabaseName("ux_payment_idempotency_operation");

                    b.ToTable("payment_idempotency", "lou");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", "lou");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "lou");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "lou");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "lou");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "lou");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Appointments.Appointment", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Staff.BarberProfile", null)
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LouBarbershop.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LouBarbershop.Domain.Catalog.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Catalog.BarberServiceOffering", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Staff.BarberProfile", null)
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LouBarbershop.Domain.Catalog.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Commissions.CommissionEntry", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Staff.BarberProfile", null)
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LouBarbershop.Domain.Sales.SaleItem", null)
                        .WithOne()
                        .HasForeignKey("LouBarbershop.Domain.Commissions.CommissionEntry", "SaleItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LouBarbershop.Domain.Commissions.CommissionEntry", null)
                        .WithOne()
                        .HasForeignKey("LouBarbershop.Domain.Commissions.CommissionEntry", "SourceEntryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LouBarbershop.Domain.Commissions.CommissionRule", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Staff.BarberProfile", null)
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Commissions.Settlement", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Staff.BarberProfile", null)
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Commissions.SettlementAdjustment", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Commissions.Settlement", null)
                        .WithMany("Adjustments")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Commissions.SettlementItem", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Commissions.CommissionEntry", null)
                        .WithOne()
                        .HasForeignKey("LouBarbershop.Domain.Commissions.SettlementItem", "CommissionEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LouBarbershop.Domain.Commissions.Settlement", null)
                        .WithMany("Items")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Expenses.Expense", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Expenses.ExpenseCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Inventory.InventoryMovement", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LouBarbershop.Domain.Inventory.InventoryReceiptItem", null)
                        .WithOne()
                        .HasForeignKey("LouBarbershop.Domain.Inventory.InventoryMovement", "ReceiptItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LouBarbershop.Domain.Sales.SaleItem", null)
                        .WithMany()
                        .HasForeignKey("SaleItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LouBarbershop.Domain.Inventory.InventoryReceiptItem", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LouBarbershop.Domain.Inventory.InventoryReceipt", null)
                        .WithMany("Items")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Sales.Payment", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Sales.SaleOperation", null)
                        .WithMany("Payments")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Sales.SaleItem", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Staff.BarberProfile", null)
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LouBarbershop.Domain.Sales.SaleOperation", null)
                        .WithMany("Items")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LouBarbershop.Domain.Catalog.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LouBarbershop.Domain.Catalog.Service", null)
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("LouBarbershop.Domain.Sales.SaleOperation", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Appointments.Appointment", null)
                        .WithOne()
                        .HasForeignKey("LouBarbershop.Domain.Sales.SaleOperation", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LouBarbershop.Domain.Staff.BarberProfile", null)
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LouBarbershop.Domain.Customers.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Scheduling.AvailabilityExceptionRule", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Staff.BarberProfile", null)
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Scheduling.WorkingSchedule", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Staff.BarberProfile", null)
                        .WithMany()
                        .HasForeignKey("BarberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Staff.BarberProfile", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Staff.StaffProfile", null)
                        .WithOne()
                        .HasForeignKey("LouBarbershop.Domain.Staff.BarberProfile", "StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Staff.StaffProfile", b =>
                {
                    b.HasOne("LouBarbershop.Infrastructure.Identity.AppUser", null)
                        .WithOne()
                        .HasForeignKey("LouBarbershop.Domain.Staff.StaffProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Infrastructure.Persistence.AppointmentEventRecord", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Appointments.Appointment", null)
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Infrastructure.Persistence.IdempotencyRow", b =>
                {
                    b.HasOne("LouBarbershop.Domain.Sales.SaleOperation", null)
                        .WithOne()
                        .HasForeignKey("LouBarbershop.Infrastructure.Persistence.IdempotencyRow", "OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("LouBarbershop.Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("LouBarbershop.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("LouBarbershop.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("LouBarbershop.Infrastructure.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LouBarbershop.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("LouBarbershop.Infrastructure.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LouBarbershop.Domain.Commissions.Settlement", b =>
                {
                    b.Navigation("Adjustments");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Inventory.InventoryReceipt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LouBarbershop.Domain.Sales.SaleOperation", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
