"""Agregar telefono y correo a empleados

Revision ID: 6e14db085410
Revises: 70c526a80354
Create Date: 2025-06-05 22:07:10.004791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e14db085410'
down_revision = '70c526a80354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('correo', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empleados', schema=None) as batch_op:
        batch_op.drop_column('correo')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
