"""agregar_campo_descripcion_servicios

Revision ID: 70c526a80354
Revises: bd992161ff9d
Create Date: 2025-06-02 21:48:36.836788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c526a80354'
down_revision = 'bd992161ff9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicios', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
